#!/bin/sh

: ${SSH_DIR:=".joker/ssh"}
: ${SSH_KEY:="$SSH_DIR/id_ed25519"}
: ${USER_NAME:="joker"}
: ${REMOTE_HOST:="127.0.0.1"}
: ${REMOTE_PORT:=2222}

ssh_opts=$(printf "%q " -i "$SSH_KEY" -o UserKnownHostsFile="$SSH_DIR/known_hosts")
exec ssh $ssh_opts -p "$REMOTE_PORT" "$USER_NAME@$REMOTE_HOST" "$@"
