#!/bin/sh

set -e

: ${FBSD_NIC_TYPE:=vtnet}

export ASSUME_ALWAYS_YES=yes 

bridge0_net="192.168.57"

# configure bridge module
kldstat -q -m if_bridge || kldload if_bridge
sysctl net.link.bridge.pfil_onlyip=0
sysctl net.link.bridge.pfil_bridge=0
sysctl net.link.bridge.pfil_member=0

cat >> /etc/sysctl.conf << EOF

net.link.bridge.pfil_onlyip=0  # Only pass IP packets when pfil is enabled
net.link.bridge.pfil_bridge=0  # Packet filter on the bridge interface
net.link.bridge.pfil_member=0  # Packet filter on the member interface
EOF

# create bridge0 interface
ifconfig bridge0 create inet "${bridge0_net}.1/24"
sysrc cloned_interfaces="bridge0"
sysrc ifconfig_bridge0="inet ${bridge0_net}.1/24"

# enable forwarding
sysctl net.inet.ip.forwarding=1
sysrc gateway_enable="YES"

# enable nat
kldstat -q -m pf || kldload pf

cat > /etc/pf.conf << EOF
ext_if="${FBSD_NIC_TYPE}0"
int_if="bridge0"

set skip on lo0
nat on \$ext_if from \$int_if:network to any -> (\$ext_if)

pass in all
pass out all
EOF

pfctl -f /etc/pf.conf
pfctl -e
sysrc pf_enable="YES"

# enable dhcp on bridge0
cat > /usr/local/etc/dnsmasq.conf << EOF
interface=bridge0
dhcp-range=${bridge0_net}.11,${bridge0_net}.250,24h
dhcp-option=3,${bridge0_net}.1  # gateway
dhcp-option=6,${bridge0_net}.1  # dns
EOF

sysrc dnsmasq_enable="YES"
service dnsmasq start
