#!/bin/sh

set -e

: ${FBSD_NIC_TYPE:=vtnet}

# load nic modules
for nic_type in $FBSD_NIC_TYPE bridge epair; do
    if kldstat -q -m "if_$nic_type"; then
        continue
    fi

    if ! kldload "if_$nic_type"; then
        continue
    fi

    echo "if_${nic_type}_load=YES" >> /boot/loader.conf
done
