#!/bin/sh

set -e

: ${FBSD_NIC_TYPE:=vtnet}

if ifconfig bridge0 create; then
    ifconfig bridge0 addm ${FBSD_NIC_TYPE}0

    sysrc cloned_interfaces="bridge0"
    sysrc ifconfig_bridge0="addm ${FBSD_NIC_TYPE}0 up"
fi
