#!/bin/sh

template_name=go-dev-template

# Создаем, если не существует
if iocage create -r LATEST -n "$template_name" dhcp=on; then
    # Настраиваем
    iocage exec -f "$template_name" pkg install -y go git bash curl
    iocage stop "$template_name"
    # Превращаем в шаблон
    iocage set template=yes "$template_name" 
fi
