#!/bin/sh

set -e

export ASSUME_ALWAYS_YES=yes 

pkg install -y py311-iocage

# ioc_start.py: Stop passing allow.dying argument #87
(
    cd /usr/local/lib/python3.11/site-packages/iocage_lib && \
    patch -N << EOF
--- ioc_start.py.orig   2025-12-23 17:57:44.059470000 +0000
+++ ioc_start.py        2025-12-23 18:00:07.993981000 +0000
@@ -590,7 +590,6 @@
                 f'exec.timeout={exec_timeout}',
                 f'stop.timeout={stop_timeout}',
                 f'mount.fstab={self.path}/fstab',
-                'allow.dying',
                 f'exec.consolelog={self.iocroot}/log/ioc-'
                 f'{self.uuid}-console.log',
                 f'ip_hostname={ip_hostname}' if ip_hostname else '',
EOF
)

iocage activate workpool
