#!/bin/sh

set -e

usage="Usage: $0 <name> <path>"
name=${1:?$usage}
path=${2:?$usage}

rc_name="mount_$name"
rc_script="/usr/local/etc/rc.d/$rc_name"

# NOTE: Не верь `mount_vboxvfs -h`!
# По умолчанию файловая система монтируется RW с правами 0777.
# Использование опции -r (-o ro) приводит к ошибке.
# Флаг --readonly на стороне хост-компьютера решает.
cat > "$rc_script" << EOF
#!/bin/sh

# PROVIDE: $rc_name
# REQUIRE: DAEMON vboxguest
# BEFORE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="$rc_name"
rcvar="${rc_name}_enable"

start_cmd="mkdir -p '$path' && mount -t vboxvfs '$name' '$path'"
stop_cmd="umount '$name'"

load_rc_config \$name
run_rc_command "\$1"
EOF

chmod +x "$rc_script"

sysrc   "${rc_name}_enable"="YES"
service "$rc_name" start
